package com.diffblue.demo.ecommerce.controllers;

import com.diffblue.deeptestutils.Reflector;
import com.diffblue.demo.ecommerce.controllers.GlobalExceptionHandler;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class GlobalExceptionHandlerTest {

  @Rule public ExpectedException thrown = ExpectedException.none();
  @Rule public Timeout globalTimeout = new Timeout(10000);

  /* testedClasses: GlobalExceptionHandler */
  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void constructorOutputVoid() {

    // Act, creating object to test constructor
    final GlobalExceptionHandler objectUnderTest = new GlobalExceptionHandler();

    // Method returns void, testing that no exception is thrown
  }

  /*
   * Test generated by Diffblue Cover.
   * This test case covers the entire method.
   */

  @Test
  public void defaultExceptionHandlerInputNotNullOutputNotNull()
      throws InvocationTargetException, Exception {

    // Arrange
    final GlobalExceptionHandler objectUnderTest = new GlobalExceptionHandler();
    final Exception exception = (Exception)Reflector.getInstance("java.lang.Exception");
    Reflector.setField(exception, "cause", null);
    Reflector.setField(exception, "detailMessage", null);

    // Act
    final String retval = objectUnderTest.defaultExceptionHandler(exception);

    // Assert result
    Assert.assertEquals("redirect:/exception", retval);
  }
}
